package com.kalavakuri.webmvc.business.constant;

public class BusinessConstants {

	public static final String FAMILY_INSERT_QUERY = "INSERT INTO FAMILY(FAMILY_ID, FAMILY_MEMBER_NAME, FAMILY_MEMBER_AGE) VALUES (?,?,?)";
	public static final String FAMILY_ADDRESS_INSERT_QUERY = "INSERT INTO FAMILY_ADDRESS(FAMILY_ID, ADDRESS_ID, FAMILY_ADDRESS) VALUES (?,?,?)";
	public static final String FAMILY_SELECT_QUERY = "SELECT FAMILY.FAMILY_ID, FAMILY.FAMILY_MEMBER_NAME, FAMILY.FAMILY_MEMBER_AGE, FAMILY_ADDRESS.FAMILY_ADDRESS FROM FAMILY INNER JOIN FAMILY_ADDRESS ON FAMILY.FAMILY_ID = FAMILY_ADDRESS.FAMILY_ID ORDER BY FAMILY.FAMILY_ID";
	public static final String FAMILY_MEMBER_COUNT = "SELECT NVL(MAX(FAMILY_ID),0) + 1 AS FAMILY_MEMBER_COUNT FROM FAMILY";
	public static final String FAMILY_MEMBER_ADDRESS_COUNT = "SELECT NVL(MAX(ADDRESS_ID),0) + 1 AS FAMILY_MEMBER_ADDRESS_COUNT FROM FAMILY_ADDRESS";
	public static final String FAMILY_FAMILY_ID = "FAMILY_ID";
	public static final String FAMILY_FAMILY_MEMBER_NAME = "FAMILY_MEMBER_NAME";
	public static final String FAMILY_FAMILY_MEMBER_AGE = "FAMILY_MEMBER_AGE";
	public static final String FAMILY_ADDRESS = "FAMILY_ADDRESS";
}
